CREATE TABLE IF NOT EXISTS `SUBJECT` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `GENDER` CHAR(1) NOT NULL,
  `HEIGHT` DECIMAL NOT NULL,
  `WEIGHT` DECIMAL NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB